services:
  # Servicio de PHP-FPM para Symfony
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - database
    environment:
      DATABASE_URL: "mysql://symfony_user:rootpassword@database:3306/symfony?serverVersion=8.0&dbname_suffix="
    networks:
      - symfony_network

  # Servicio de MySQL
  database:
    image: mysql:8.0
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony_user
      MYSQL_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony_network

  fixtures:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_fixtures
    depends_on:
      - database
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    environment:
      DATABASE_URL: "mysql://symfony_user:rootpassword@database:3306/symfony?serverVersion=8.0&dbname_suffix="
    command: >
      sh -c "while ! nc -z database 3306; do sleep 1; done &&
             php bin/console doctrine:migrations:migrate -n &&
             php bin/console doctrine:fixtures:load -n"
    networks:
      - symfony_network

volumes:
  db_data:

networks:
  symfony_network:
    driver: bridge
