controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
products:
    path: /products
    controller: App\Controller\ProductController::getProducts
    methods: GET